on:
  push:
    tags:
      - '*'
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull qyrio/eosio-dev
        run: docker pull qryio/eosio-dev:latest
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...